const params = new URLSearchParams(window.location.search);
const PLAYER_ID = params.get('id') || 'joueur1';
const PLAYER_META = getPlayerMeta(PLAYER_ID);
const STORAGE_KEY = `personnage_${PLAYER_ID}`;
const UI_STORAGE_KEY = `personnage_ui_${PLAYER_ID}`;
const MAX_VAL = 5, MAX_ACT = 3, MAX_LVL = 10, BASE_PV = 6;
const CRIT_FACES = [6, 5, 4];
const DIE_DOTS = { 4: [[.3,.3],[.7,.3],[.3,.7],[.7,.7]], 5: [[.3,.3],[.7,.3],[.5,.5],[.3,.7],[.7,.7]], 6: [[.3,.25],[.7,.25],[.3,.5],[.7,.5],[.3,.75],[.7,.75]] };
let currentClassData = null;

function dieSVG(n) { return `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">${(DIE_DOTS[n] || []).map(([cx, cy]) => `<circle class="die-dot" cx="${cx * 20}" cy="${cy * 20}" r="2.3"/>`).join('')}</svg>`; }
function escapeAttr(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;'); }
function escapeText(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); }
function defaultStyles() { return Object.fromEntries(STATS.map(s => [s.key, ''])); }
function defaultSheetState() { return { niveau: 1, carac: Object.fromEntries(STATS.map(c => [c.key, { val: 1, act: 1, crit: [true, false, false] }])), pv: Array.from({ length: BASE_PV }, () => ({ lost: false })), equipement: { main1: { nom: '', valeur: '', desc: '' }, main2: { nom: '', valeur: '', desc: '' }, armure: { nom: '', valeur: '', desc: '' } }, inventaire: Array.from({ length: 6 }, () => '') }; }
function defaultPlayerState() { return { id: PLAYER_ID, joueur: PLAYER_META.label, nom: PLAYER_META.personnage, classeId: PLAYER_META.classeId, styles: defaultStyles(), sheet: defaultSheetState(), tree: TREE_STATE_DEFAULT(), progression: defaultProgressionState() }; }
let state = defaultPlayerState();
let statusTimer = null;
function normalizeSheet(sheet) { const fallback = defaultSheetState(); const normalized = { ...fallback, ...(sheet ?? {}) }; normalized.carac = normalized.carac ?? {}; normalized.carac = Object.fromEntries(STATS.map(({ key }) => [key, normalized.carac[key] ?? fallback.carac[key]])); normalized.pv = Array.isArray(normalized.pv) ? normalized.pv : fallback.pv; normalized.niveau = Number.isInteger(normalized.niveau) ? normalized.niveau : fallback.niveau; normalized.equipement = { main1: { nom: normalized.equipement?.main1?.nom ?? '', valeur: normalized.equipement?.main1?.valeur ?? '', desc: normalized.equipement?.main1?.desc ?? '' }, main2: { nom: normalized.equipement?.main2?.nom ?? '', valeur: normalized.equipement?.main2?.valeur ?? '', desc: normalized.equipement?.main2?.desc ?? '' }, armure: { nom: normalized.equipement?.armure?.nom ?? '', valeur: normalized.equipement?.armure?.valeur ?? '', desc: normalized.equipement?.armure?.desc ?? '' } }; normalized.inventaire = Array.from({ length: 6 }, (_, i) => normalized.inventaire?.[i] ?? ''); return normalized; }
function normalizeStyles(styles) { const fallback = defaultStyles(); return Object.fromEntries(STATS.map(({ key }) => [key, styles?.[key] ?? fallback[key]])); }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); showStatus('Sauvegardé automatiquement'); }
function load() { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return; state = { ...defaultPlayerState(), ...JSON.parse(raw) }; state.sheet = normalizeSheet(state.sheet); state.styles = normalizeStyles(state.styles); state.tree = normalizeTreeState(state.tree, state.classeId); state.progression = normalizeProgressionState(state.progression); } catch {} }
function showStatus(message) { const el = document.getElementById('save-status'); if (!el) return; el.textContent = message; clearTimeout(statusTimer); statusTimer = setTimeout(() => { el.textContent = ''; }, 1800); }
function toggleIdentityPanel() { const panel = document.getElementById('identity-panel'); panel.classList.toggle('is-closed'); localStorage.setItem(UI_STORAGE_KEY, JSON.stringify({ identityClosed: panel.classList.contains('is-closed') })); }
function restoreIdentityPanel() { try { const raw = localStorage.getItem(UI_STORAGE_KEY); if (!raw) return; const ui = JSON.parse(raw); if (ui.identityClosed) document.getElementById('identity-panel').classList.add('is-closed'); } catch {} }
function renderClassSelect() { const select = document.getElementById('class-select'); select.innerHTML = CLASSES.map(cls => `<option value="${cls.id}"${cls.id === state.classeId ? ' selected' : ''}>${cls.nom}</option>`).join(''); select.onchange = async () => { state.classeId = select.value; state.tree = normalizeTreeState(null, state.classeId); save(); await loadAndRenderTree(); renderAll(); }; }
function renderIdentity() { document.getElementById('player-label').textContent = state.joueur || PLAYER_META.label; document.getElementById('player-title').textContent = state.nom || 'Nouveau personnage'; const classMeta = getClassMeta(state.classeId); document.getElementById('player-subtitle').textContent = `${classMeta.article} ${classMeta.nom}`; const playerInput = document.getElementById('player-name'); playerInput.value = state.joueur; playerInput.oninput = () => { state.joueur = playerInput.value; document.getElementById('player-label').textContent = state.joueur || PLAYER_META.label; save(); }; const characterInput = document.getElementById('character-name'); characterInput.value = state.nom; characterInput.oninput = () => { state.nom = characterInput.value; document.getElementById('player-title').textContent = state.nom || 'Nouveau personnage'; save(); }; }
function renderStylesConfig() { const grid = document.getElementById('style-grid'); grid.innerHTML = ''; STATS.forEach(({ key, label }) => { const wrap = document.createElement('div'); wrap.className = 'field-group'; wrap.innerHTML = `<label class="field-label" for="style-${key}">Style de ${label}</label><input class="sheet-input" id="style-${key}" type="text" placeholder="Ex. brutal, précis, mystique" value="${escapeAttr(state.styles[key])}">`; const input = wrap.querySelector('input'); input.oninput = () => { state.styles[key] = input.value; save(); renderSheetCaracs(); }; grid.appendChild(wrap); }); }
function renderClassPreview() { const classMeta = getClassMeta(state.classeId); document.getElementById('class-preview').innerHTML = `<div class="class-preview-icon"><img src="${classMeta.icone}" alt="${classMeta.nom}" onerror="this.style.display='none'"></div><div><div class="class-preview-name">${classMeta.article} ${classMeta.nom}</div><div class="class-preview-desc">${classMeta.ambiance}</div></div>`; }
function renderSheetLevel() { const row = document.getElementById('sheet-level-bar'); row.innerHTML = ''; for (let i = 0; i < MAX_LVL; i++) { const level = i + 1; const pip = document.createElement('div'); pip.className = ['level-pip', level <= state.sheet.niveau ? 'filled' : '', level === state.sheet.niveau ? 'current' : ''].filter(Boolean).join(' '); pip.textContent = level; pip.title = `Niveau ${level}`; pip.onclick = () => { state.sheet.niveau = level; save(); renderSheetLevel(); renderTreeOnly(); }; row.appendChild(pip); } }
function renderSheetCaracs() { const grid = document.getElementById('sheet-carac-grid'); grid.innerHTML = ''; STATS.forEach(({ key, label }) => { const data = state.sheet.carac[key]; const style = state.styles?.[key] ?? ''; const col = document.createElement('div'); col.className = 'carac-col'; col.innerHTML = `<div class="carac-head"><div class="carac-name">${label}</div><div class="carac-style">${escapeText(style)}</div></div>`; const valRow = document.createElement('div'); valRow.className = 'billes-row'; for (let i = 0; i < MAX_VAL; i++) { const value = i + 1; const b = document.createElement('div'); b.className = `bille${value <= data.val ? ' filled' : ''}${value === 1 ? ' fixed' : ''}`; b.title = `${label} ${value}`; b.onclick = () => { state.sheet.carac[key].val = value; save(); renderSheetCaracs(); }; valRow.appendChild(b); } col.appendChild(valRow); const critBlock = document.createElement('div'); critBlock.className = 'crit-block'; critBlock.innerHTML = '<div class="block-label">Critique</div>'; const diceRow = document.createElement('div'); diceRow.className = 'crit-dice'; CRIT_FACES.forEach((face, fi) => { const die = document.createElement('div'); die.innerHTML = dieSVG(face); die.className = `die-face${data.crit[fi] ? ' active' : ''}${fi === 0 ? ' fixed' : ''}`; die.title = `CRIT ${label} : ${face}`; if (fi > 0) die.onclick = () => { state.sheet.carac[key].crit[fi] = !state.sheet.carac[key].crit[fi]; if (!state.sheet.carac[key].crit[1]) state.sheet.carac[key].crit[2] = false; save(); renderSheetCaracs(); }; diceRow.appendChild(die); }); critBlock.appendChild(diceRow); col.appendChild(critBlock); const actBlock = document.createElement('div'); actBlock.className = 'actions-block'; actBlock.innerHTML = '<div class="block-label">Actions / tour</div>'; const actRow = document.createElement('div'); actRow.className = 'billes-row'; for (let i = 0; i < MAX_ACT; i++) { const value = i + 1; const b = document.createElement('div'); b.className = `bille${value <= data.act ? ' filled' : ''}${value === 1 ? ' fixed' : ''}`; b.title = `${label} : ${value} action${value > 1 ? 's' : ''}/tour`; b.onclick = () => { state.sheet.carac[key].act = value; save(); renderSheetCaracs(); }; actRow.appendChild(b); } actBlock.appendChild(actRow); col.appendChild(actBlock); grid.appendChild(col); }); }
function renderSheetPV() { const row = document.getElementById('sheet-hearts-row'); row.innerHTML = ''; state.sheet.pv.forEach((h, i) => { const el = document.createElement('span'); el.className = `heart ${h.lost ? 'lost' : 'full'}`; el.textContent = '♥'; el.title = h.lost ? 'Blessure — cliquer pour récupérer' : 'PV — cliquer pour perdre'; el.onclick = () => { state.sheet.pv[i].lost = !state.sheet.pv[i].lost; save(); renderSheetPV(); }; row.appendChild(el); }); }
function renderSheetEquipement() { const grid = document.getElementById('sheet-equipement-grid'); grid.innerHTML = ''; [{ key: 'main1', title: 'Main principale', valueLabel: 'DEG' }, { key: 'main2', title: 'Main secondaire', valueLabel: 'DEG' }, { key: 'armure', title: 'Armure', valueLabel: 'ARM' }].forEach(item => { const data = state.sheet.equipement[item.key]; const card = document.createElement('div'); card.className = 'equipement-card'; card.innerHTML = `<div class="equipement-title">${item.title}</div><div class="equipement-row"><input class="sheet-input" type="text" placeholder="Nom de l'objet" value="${escapeAttr(data.nom)}"><input class="sheet-input" type="text" placeholder="${item.valueLabel}" value="${escapeAttr(data.valeur)}"></div><textarea class="sheet-textarea" placeholder="Description">${escapeText(data.desc)}</textarea>`; const [nomInput, valeurInput] = card.querySelectorAll('input'); const descInput = card.querySelector('textarea'); nomInput.oninput = () => { state.sheet.equipement[item.key].nom = nomInput.value; save(); }; valeurInput.oninput = () => { state.sheet.equipement[item.key].valeur = valeurInput.value; save(); }; descInput.oninput = () => { state.sheet.equipement[item.key].desc = descInput.value; save(); }; grid.appendChild(card); }); }
function renderSheetInventaire() {
  const grid = document.getElementById('sheet-inventaire-grid');
  grid.innerHTML = '';

  state.sheet.inventaire.forEach((value, i) => {
    const input = document.createElement('textarea');
    input.className = 'sheet-textarea inventory-textarea inventaire-slot';
    input.placeholder = `Objet ${i + 1}`;
    input.rows = 2;
    input.value = value;

    input.oninput = () => {
      state.sheet.inventaire[i] = input.value;
      save();
    };

    grid.appendChild(input);
  });
}
function renderSheet() { renderSheetLevel(); renderSheetCaracs(); renderSheetPV(); renderSheetEquipement(); renderSheetInventaire(); }
function renderTreeOnly() { if (!currentClassData) return; ensurePlayerTreeState(state); renderPlayerTree({ containerId:'player-tree-root', classId:state.classeId, classData:currentClassData, treeState:state.tree, playerLevel:state.sheet.niveau, onChange: treeState => { state.tree = treeState; save(); renderTreeOnly(); } }); }
async function loadAndRenderTree() { const root = document.getElementById('player-tree-root'); root.innerHTML = '<div class="placeholder-panel">Chargement de l’arbre…</div>'; try { ensurePlayerTreeState(state); currentClassData = await loadClassScript(state.classeId); renderTreeOnly(); } catch (err) { root.innerHTML = `<div class="tree-error">${err.message}</div>`; } }
function renderAll() { renderIdentity(); renderClassSelect(); renderStylesConfig(); renderClassPreview(); renderSheet(); restoreIdentityPanel(); }
load(); renderAll(); loadAndRenderTree();
