const params = new URLSearchParams(window.location.search);
const PLAYER_ID = params.get('id') || 'joueur1';
const PLAYER_META = getPlayerMeta(PLAYER_ID);
const STORAGE_KEY = `personnage_${PLAYER_ID}`;
const UI_STORAGE_KEY = `personnage_ui_${PLAYER_ID}`;
const MAX_LVL = 10, BASE_PV = 6;
const CRIT_FACES = [6, 5, 4];
const DIE_DOTS = { 4: [[.3,.3],[.7,.3],[.3,.7],[.7,.7]], 5: [[.3,.3],[.7,.3],[.5,.5],[.3,.7],[.7,.7]], 6: [[.3,.25],[.7,.25],[.3,.5],[.7,.5],[.3,.75],[.7,.75]] };
let currentClassData = null;
function dieSVG(n) { return `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">${(DIE_DOTS[n] || []).map(([cx, cy]) => `<circle class="die-dot" cx="${cx * 20}" cy="${cy * 20}" r="2.3"/>`).join('')}</svg>`; }
function escapeAttr(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;'); }
function escapeText(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); }
function defaultStyles() { return Object.fromEntries(STATS.map(s => [s.key, ''])); }
function defaultEquipmentState() { return Object.fromEntries(EQUIPMENT_SLOTS.map(({ key }) => [key, { nom: '', valeur: '', desc: '' }])); }
function defaultSheetState() { return { niveau: 1, pvLost: [], equipement: defaultEquipmentState(), inventaire: Array.from({ length: 6 }, () => '') }; }
function defaultPlayerState() { return { id: PLAYER_ID, joueur: PLAYER_META.label, nom: PLAYER_META.personnage, classeId: PLAYER_META.classeId, styles: defaultStyles(), sheet: defaultSheetState(), tree: TREE_STATE_DEFAULT(), progression: defaultProgressionState() }; }
let state = defaultPlayerState();
let statusTimer = null;
function normalizeSheet(sheet) { const fallback = defaultSheetState(); const normalized = { ...fallback, ...(sheet ?? {}) }; normalized.niveau = Number.isInteger(normalized.niveau) ? normalized.niveau : fallback.niveau; normalized.pvLost = Array.isArray(normalized.pvLost) ? normalized.pvLost : (Array.isArray(normalized.pv) ? normalized.pv.map(h => !!h.lost) : []); normalized.equipement = Object.fromEntries(EQUIPMENT_SLOTS.map(({ key }) => [key, { nom: normalized.equipement?.[key]?.nom ?? '', valeur: normalized.equipement?.[key]?.valeur ?? '', desc: normalized.equipement?.[key]?.desc ?? '' }])); normalized.inventaire = Array.from({ length: 6 }, (_, i) => normalized.inventaire?.[i] ?? ''); return normalized; }
function normalizeStyles(styles) { const fallback = defaultStyles(); return Object.fromEntries(STATS.map(({ key }) => [key, styles?.[key] ?? fallback[key]])); }
function getComputedSheet() { return computeSheetFromProgression({ stats: STATS, level: state.sheet.niveau, progression: state.progression }); }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); showStatus('Sauvegardé automatiquement'); }
function load() { try { const raw = localStorage.getItem(STORAGE_KEY); if (!raw) return; state = { ...defaultPlayerState(), ...JSON.parse(raw) }; state.sheet = normalizeSheet(state.sheet); state.styles = normalizeStyles(state.styles); state.tree = normalizeTreeState(state.tree, state.classeId); state.progression = normalizeProgressionState(state.progression); } catch {} }
function showStatus(message) { const el = document.getElementById('save-status'); if (!el) return; el.textContent = message; clearTimeout(statusTimer); statusTimer = setTimeout(() => { el.textContent = ''; }, 1800); }
function toggleIdentityPanel() { const panel = document.getElementById('identity-panel'); panel.classList.toggle('is-closed'); localStorage.setItem(UI_STORAGE_KEY, JSON.stringify({ identityClosed: panel.classList.contains('is-closed') })); }
function toggleProgressionPanel() { const panel = document.getElementById('progression-panel'); panel.classList.toggle('is-closed'); const raw = localStorage.getItem(UI_STORAGE_KEY); const ui = raw ? JSON.parse(raw) : {}; ui.progressionClosed = panel.classList.contains('is-closed'); localStorage.setItem(UI_STORAGE_KEY, JSON.stringify(ui)); }
function restoreIdentityPanel() { try { const raw = localStorage.getItem(UI_STORAGE_KEY); if (!raw) return; const ui = JSON.parse(raw); if (ui.identityClosed) document.getElementById('identity-panel').classList.add('is-closed'); if (ui.progressionClosed) document.getElementById('progression-panel')?.classList.add('is-closed'); } catch {} }
function renderClassSelect() { const select = document.getElementById('class-select'); select.innerHTML = CLASSES.map(cls => `<option value="${cls.id}"${cls.id === state.classeId ? ' selected' : ''}>${cls.nom}</option>`).join(''); select.onchange = async () => { state.classeId = select.value; state.tree = normalizeTreeState(null, state.classeId); save(); await loadAndRenderTree(); renderAll(); }; }
function renderIdentity() { document.getElementById('player-label').textContent = state.joueur || PLAYER_META.label; document.getElementById('player-title').textContent = state.nom || 'Nouveau personnage'; const classMeta = getClassMeta(state.classeId); document.getElementById('player-subtitle').textContent = `${classMeta.article} ${classMeta.nom}`; const playerInput = document.getElementById('player-name'); playerInput.value = state.joueur; playerInput.oninput = () => { state.joueur = playerInput.value; document.getElementById('player-label').textContent = state.joueur || PLAYER_META.label; save(); }; const characterInput = document.getElementById('character-name'); characterInput.value = state.nom; characterInput.oninput = () => { state.nom = characterInput.value; document.getElementById('player-title').textContent = state.nom || 'Nouveau personnage'; save(); }; }
function renderStylesConfig() { const grid = document.getElementById('style-grid'); grid.innerHTML = ''; STATS.forEach(({ key, label }) => { const wrap = document.createElement('div'); wrap.className = 'field-group'; wrap.innerHTML = `<label class="field-label" for="style-${key}">Style de ${label}</label><input class="sheet-input" id="style-${key}" type="text" placeholder="Ex. brutal, précis, mystique" value="${escapeAttr(state.styles[key])}">`; const input = wrap.querySelector('input'); input.oninput = () => { state.styles[key] = input.value; save(); renderSheetCaracs(); }; grid.appendChild(wrap); }); }
function renderClassPreview() { const classMeta = getClassMeta(state.classeId); document.getElementById('class-preview').innerHTML = `<div class="class-preview-icon"><img src="${classMeta.icone}" alt="${classMeta.nom}" onerror="this.style.display='none'"></div><div><div class="class-preview-name">${classMeta.article} ${classMeta.nom}</div><div class="class-preview-desc">${classMeta.ambiance}</div></div>`; }
function renderSheetLevel() { const row = document.getElementById('sheet-level-bar'); row.innerHTML = ''; for (let i = 0; i < MAX_LVL; i++) { const level = i + 1; const pip = document.createElement('div'); pip.className = ['level-pip', level <= state.sheet.niveau ? 'filled' : '', level === state.sheet.niveau ? 'current' : ''].filter(Boolean).join(' '); pip.textContent = level; pip.title = `Niveau ${level}`; pip.onclick = () => { setLevel(level); }; row.appendChild(pip); } }
function setLevel(level) { state.sheet.niveau = level; clearInactiveProgressionChoices(); save(); renderSheet(); renderTreeOnly(); }
function clearInactiveProgressionChoices() { state.progression = normalizeProgressionState(state.progression); Object.keys(state.progression.choices).forEach(levelKey => { const level = Number(levelKey); if (level > state.sheet.niveau) state.progression.choices[level] = defaultProgressionChoice(level); }); }
function setProgressionChoice(level, choice, stat = null) { const entry = getProgressionLevel(level); state.progression.choices[level] = { level, type: entry.type, choice, stat }; save(); renderSheet(); }
function clearProgressionChoice(level) { state.progression.choices[level] = defaultProgressionChoice(level); save(); renderSheet(); }
function hasAllowedStatChoice(level, choice) { return STATS.some(({ key }) => isProgressionChoiceAllowed({ stats: STATS, level: state.sheet.niveau, progression: state.progression, targetLevel: level, choice, stat: key })); }
function renderProgression() { const grid = document.getElementById('progression-grid'); if (!grid) return; grid.innerHTML = ''; getAvailableProgressionLevels(state.sheet.niveau).forEach(entry => { const choice = state.progression.choices[entry.level] ?? defaultProgressionChoice(entry.level); const complete = entry.type === LEVEL_TYPES.CREATION ? getCreationUsedPoints(choice) === PROGRESSION_LIMITS.creationPoints : !!choice.choice && (choice.choice === 'pv' || !!choice.stat); const card = document.createElement('div'); card.className = `progression-card${complete ? ' complete' : ''}`; card.innerHTML = `<div class="progression-head"><div class="progression-level">Niveau ${entry.level}</div><div class="progression-type">${entry.label}</div></div><div class="progression-actions"></div><div class="progression-stat-row"></div>`; const actions = card.querySelector('.progression-actions'); const statRow = card.querySelector('.progression-stat-row'); if (entry.type === LEVEL_TYPES.CREATION) addCreationChoiceButtons(actions, statRow, choice); if (entry.type === LEVEL_TYPES.AMELIORATION) renderAmeliorationProgression(entry, choice, actions, statRow); if (entry.type === LEVEL_TYPES.MAITRISE) renderMaitriseProgression(entry, choice, actions, statRow); grid.appendChild(card); }); }
function renderAmeliorationProgression(entry, choice, actions, statRow) { if (choice.choice === 'pv') return addProgressionButton(actions, '♥', true, () => clearProgressionChoice(entry.level)); if (choice.choice === 'stat' && choice.stat) return addProgressionButton(actions, `${getStatLabel(choice.stat)} +1`, true, () => clearProgressionChoice(entry.level)); addProgressionButton(actions, 'Caractéristique', false, () => setProgressionChoice(entry.level, 'stat', null), hasAllowedStatChoice(entry.level, 'stat')); addProgressionButton(actions, '♥', false, () => setProgressionChoice(entry.level, 'pv', null)); if (choice.choice === 'stat') addStatButtons(statRow, entry.level, 'stat', choice.stat); }
function renderMaitriseProgression(entry, choice, actions, statRow) { if (choice.choice === 'crit' && choice.stat) return addProgressionButton(actions, `${getStatLabel(choice.stat)} critique`, true, () => clearProgressionChoice(entry.level)); if (choice.choice === 'action' && choice.stat) return addProgressionButton(actions, `+1 action de ${getStatLabel(choice.stat)}`, true, () => clearProgressionChoice(entry.level)); addProgressionButton(actions, 'Critique', false, () => setProgressionChoice(entry.level, 'crit', null), hasAllowedStatChoice(entry.level, 'crit')); addProgressionButton(actions, 'Actions par tour', false, () => setProgressionChoice(entry.level, 'action', null), hasAllowedStatChoice(entry.level, 'action')); if (choice.choice === 'crit' || choice.choice === 'action') addStatButtons(statRow, entry.level, choice.choice, choice.stat); }
function addProgressionButton(container, label, active, onClick, enabled = true) { const btn = document.createElement('button'); btn.className = `progression-btn${active ? ' active' : ''}`; btn.type = 'button'; btn.textContent = label; btn.disabled = !enabled; btn.onclick = enabled ? onClick : null; container.appendChild(btn); }
function addCreationChoiceButtons(actions, statRow, choice) { for (let i = 0; i < PROGRESSION_LIMITS.creationPoints; i++) { const selected = choice.slots?.[i] ?? null; addProgressionButton(actions, selected ? `${getStatLabel(selected)} +1` : `Carac ${i + 1}`, !!selected, () => { choice.openSlot = choice.openSlot === i ? null : i; state.progression.choices[1] = { level: 1, type: LEVEL_TYPES.CREATION, allocation: choice.allocation ?? {}, slots: choice.slots ?? [], openSlot: choice.openSlot }; save(); renderSheet(); }); } if (Number.isInteger(choice.openSlot)) addCreationSlotStatButtons(statRow, choice.openSlot, choice); }
function addCreationSlotStatButtons(container, slotIndex, choice) { STATS.forEach(({ key, label }) => { const allowed = canSetCreationSlot(choice, slotIndex, key); const btn = document.createElement('button'); btn.className = `progression-btn${choice.slots?.[slotIndex] === key ? ' active' : ''}`; btn.type = 'button'; btn.textContent = label; btn.disabled = !allowed && choice.slots?.[slotIndex] !== key; btn.onclick = () => setCreationSlot(slotIndex, key); container.appendChild(btn); }); }
function canSetCreationSlot(choice, slotIndex, stat) { const slots = Array.from({ length: PROGRESSION_LIMITS.creationPoints }, (_, i) => choice.slots?.[i] ?? null); slots[slotIndex] = stat; const allocation = {}; slots.forEach(key => { if (key) allocation[key] = (allocation[key] ?? 0) + 1; }); return PROGRESSION_LIMITS.minStat + (allocation[stat] ?? 0) <= PROGRESSION_LIMITS.maxStat; }
function getStatLabel(key) { return STATS.find(s => s.key === key)?.label ?? key; }
function setCreationSlot(slotIndex, stat) { const choice = state.progression.choices[1] ?? defaultProgressionChoice(1); if (!canSetCreationSlot(choice, slotIndex, stat)) return; const slots = Array.from({ length: PROGRESSION_LIMITS.creationPoints }, (_, i) => choice.slots?.[i] ?? null); slots[slotIndex] = stat; const allocation = {}; slots.forEach(key => { if (key) allocation[key] = (allocation[key] ?? 0) + 1; }); state.progression.choices[1] = { level: 1, type: LEVEL_TYPES.CREATION, allocation, slots, openSlot: null }; save(); renderSheet(); }
function addStatButtons(container, level, choice, currentStat) { STATS.forEach(({ key, label }) => { const allowed = isProgressionChoiceAllowed({ stats: STATS, level: state.sheet.niveau, progression: state.progression, targetLevel: level, choice, stat: key }); const btn = document.createElement('button'); btn.className = `progression-btn${currentStat === key ? ' active' : ''}`; btn.type = 'button'; btn.textContent = label; btn.disabled = !allowed && currentStat !== key; btn.onclick = () => setProgressionChoice(level, choice, key); container.appendChild(btn); }); }
function renderSheetCaracs() { const computed = getComputedSheet(); const grid = document.getElementById('sheet-carac-grid'); grid.innerHTML = ''; STATS.forEach(({ key, label }) => { const data = computed.carac[key]; const style = state.styles?.[key] ?? ''; const col = document.createElement('div'); col.className = 'carac-col'; col.innerHTML = `<div class="carac-head"><div class="carac-name">${label}</div><div class="carac-style">${escapeText(style)}</div></div>`; const valRow = document.createElement('div'); valRow.className = 'billes-row'; for (let i = 0; i < PROGRESSION_LIMITS.maxStat; i++) { const value = i + 1; const b = document.createElement('div'); b.className = `bille${value <= data.val ? ' filled' : ''}${value === 1 ? ' fixed' : ''}`; b.title = `${label} ${value}`; valRow.appendChild(b); } col.appendChild(valRow); const critBlock = document.createElement('div'); critBlock.className = 'crit-block'; critBlock.innerHTML = '<div class="block-label">Critique</div>'; const diceRow = document.createElement('div'); diceRow.className = 'crit-dice'; CRIT_FACES.forEach((face, fi) => { const die = document.createElement('div'); die.innerHTML = dieSVG(face); die.className = `die-face${data.crit[fi] ? ' active' : ''}${fi === 0 ? ' fixed' : ''}`; die.title = `CRIT ${label} : ${face}`; diceRow.appendChild(die); }); critBlock.appendChild(diceRow); col.appendChild(critBlock); const actBlock = document.createElement('div'); actBlock.className = 'actions-block'; actBlock.innerHTML = '<div class="block-label">Actions / tour</div>'; const actRow = document.createElement('div'); actRow.className = 'billes-row'; for (let i = 0; i < PROGRESSION_LIMITS.maxActions; i++) { const value = i + 1; const b = document.createElement('div'); b.className = `bille${value <= data.act ? ' filled' : ''}${value === 1 ? ' fixed' : ''}`; b.title = `${label} : ${value} action${value > 1 ? 's' : ''}/tour`; actRow.appendChild(b); } actBlock.appendChild(actRow); col.appendChild(actBlock); grid.appendChild(col); }); }
function renderSheetPV() { const computed = getComputedSheet(); state.sheet.pvLost = Array.from({ length: computed.maxPV }, (_, i) => !!state.sheet.pvLost?.[i]); const row = document.getElementById('sheet-hearts-row'); row.innerHTML = ''; state.sheet.pvLost.forEach((lost, i) => { const el = document.createElement('span'); el.className = `heart ${lost ? 'lost' : 'full'}`; el.textContent = '♥'; el.title = lost ? 'Blessure — cliquer pour récupérer' : 'PV — cliquer pour perdre'; el.onclick = () => { state.sheet.pvLost[i] = !state.sheet.pvLost[i]; save(); renderSheetPV(); }; row.appendChild(el); }); }
function renderSheetEquipement() { const grid = document.getElementById('sheet-equipement-grid'); grid.innerHTML = ''; EQUIPMENT_SLOTS.forEach(item => { const data = state.sheet.equipement[item.key]; const card = document.createElement('div'); card.className = 'equipement-card'; card.innerHTML = `<div class="equipement-title">${item.title}</div><div class="equipement-row"><input class="sheet-input" type="text" placeholder="Nom de l'objet" value="${escapeAttr(data.nom)}"><input class="sheet-input" type="text" placeholder="${item.valueLabel}" value="${escapeAttr(data.valeur)}"></div><textarea class="sheet-textarea" placeholder="Description">${escapeText(data.desc)}</textarea>`; const [nomInput, valeurInput] = card.querySelectorAll('input'); const descInput = card.querySelector('textarea'); nomInput.oninput = () => { state.sheet.equipement[item.key].nom = nomInput.value; save(); }; valeurInput.oninput = () => { state.sheet.equipement[item.key].valeur = valeurInput.value; save(); }; descInput.oninput = () => { state.sheet.equipement[item.key].desc = descInput.value; save(); }; grid.appendChild(card); }); }
function renderSheetInventaire() { const grid = document.getElementById('sheet-inventaire-grid'); grid.innerHTML = ''; state.sheet.inventaire.forEach((value, i) => { const input = document.createElement('textarea'); input.className = 'sheet-textarea inventory-textarea inventaire-slot'; input.placeholder = `Objet ${i + 1}`; input.rows = 2; input.value = value; input.oninput = () => { state.sheet.inventaire[i] = input.value; save(); }; grid.appendChild(input); }); }
function renderSheet() { renderSheetLevel(); renderProgression(); renderSheetCaracs(); renderSheetPV(); renderSheetEquipement(); renderSheetInventaire(); }
function renderTreeOnly() { if (!currentClassData) return; ensurePlayerTreeState(state); renderPlayerTree({ containerId:'player-tree-root', classId:state.classeId, classData:currentClassData, treeState:state.tree, playerLevel:state.sheet.niveau, onChange: treeState => { state.tree = treeState; save(); renderTreeOnly(); } }); }
async function loadAndRenderTree() { const root = document.getElementById('player-tree-root'); root.innerHTML = '<div class="placeholder-panel">Chargement de l’arbre…</div>'; try { ensurePlayerTreeState(state); currentClassData = await loadClassScript(state.classeId); renderTreeOnly(); } catch (err) { root.innerHTML = `<div class="tree-error">${err.message}</div>`; } }
function renderAll() { renderIdentity(); renderClassSelect(); renderStylesConfig(); renderClassPreview(); renderSheet(); restoreIdentityPanel(); }
load(); renderAll(); loadAndRenderTree();
